### ISSUE TITLE
Export typed feedback to spreadsheet

### ISSUE THREAD

**Issue by PsychoPoo** [marcusgreen/moodle-gradingform_btec#2]
We've been using the BTEC grading form for our BTEC Music course this year and we love it - Thank you!!
 
One of my colleagues had a question which I said I would pass on to you:
 
Is there any way to export the typed feedback provided to students using this plug-in? We would like to be able to export the grades and feedback to a spreadsheet so that the data could be used as part of a mail-merge in case we ever need to produce paper-based feedback forms (which we occasionally need to do for external verification purposes).

We're using Moodle 2.7 - I've not really used Moodle 2.8 properly yet so I'm not sure about the changes to gradebook and how they affect things.
 
Hop that this makes sense.
 
Thanks again.

**Comment by marcusgreen** [comment]
Thank you for your feedback, it is appreciated. I cannot think of any way to do this at the moment, but I have started to look into how to create a query that would be the basis of a report or export. I will let you know when I have made some progress.

**Comment by marcusgreen** [comment]
Dear PsychoPoo, I have set up a course that demonstrates a plugin to do what you are asking for. Send an email to marcusavgreen at gmail dot com and I will give you further details.
