### ISSUE TITLE
Sum of points for all quiz attempts ?

### ISSUE THREAD

**Issue by miroi** [marcusgreen/moodle-gradingform_btec#6]
Hello,

I would like to ask if it is possible to have sum of all points of all quiz attempts per user ?

Thanks.

**Comment by marcusgreen** [comment]
I don't understand, this plugin has no connection with quiz. Could you explain further?

**Comment by miroi** [comment]
Sorry, I was wrong - it is not used in connection with Quiz...closing this ticket as irrelevant.
