### ISSUE TITLE
Fix the i_add_to_section_and_i_fill_the_form_with deprecation for Moodle 4.4

### ISSUE THREAD

**Issue by Julian-Tovar** [marcusgreen/moodle-gradingform_btec#7]
Good day team,

In Moodle 4.4 this Behat step was deprecated:

``` behat
When I add a "Assignment" to section "1" and I fill the form with:
```

In file 'tests/behat/edit_btec.feature', you can see these steps:

``` behat
And I am on "Course 1" course homepage with editing mode on
And I add a "Assignment" to section "1" and I fill the form with:
```

These steps can be replaced using the new Moodle 4.4 steps like this:

``` behat
And I add an "assign" activity to course "Course 1" section "1" and I fill the form with:
```

Fear not, it is okay to remove the `And I am on "Course 1" course homepage with editing mode on` line, the new step is equivalent to going to Course 1, and being on Course 1.

If you consider this helpful, I have created this .patch which contains this change, ready to be git applied: 
[0001-INT-20385-gradingform_btec-mod_hsuforum-Fixed-the-i_.patch](https://github.com/user-attachments/files/17262539/0001-INT-20385-gradingform_btec-mod_hsuforum-Fixed-the-i_.patch)

Please consider using this patch to fix this issue.

Thank you.

**Comment by marcusgreen** [comment]
Thanks Julian I will take a look at that. I was going to have a look at 4.5 compatibility (due out on Monday).
Have you seen the report that works with BTEC grading.
https://github.com/marcusgreen/moodle-report_advancedgrading?tab=readme-ov-file#readme

**Comment by Julian-Tovar** [comment]
Hi there Marcus, thank you. Yes I had checked out report_advancedgrading.

Let me know of anything needed pertaining the Behat step deprecation. Thank you.

**Comment by marcusgreen** [comment]
I have incorporated your change and added a note in the changelog, see
https://github.com/marcusgreen/moodle-gradingform_btec/blob/master/changelog.md
Many thanks. I will now close the ticket.
